# This workflow will do a clean install of node dependencies, build the source code, then push changes direct to master.

name: Build & Push Blocks

on:
  push:
    branches: 
    - master
    paths-ignore:
      - 'build/**'

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node 12.
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Clean install dependencies
      run: npm ci
    - name: Run production build
      run: npm run build
    - name: Push production files to master
      run: |
          git config --global user.name 'young295'
          git config --global user.email 'young295@purdue.edu'
          git add build
          git commit -am "Automated build"
          git push
      continue-on-error: true